/**
 * Shared Linux systemd service manager for abmind daemon (#1453).
 *
 * This module is the single place where the systemd unit is rendered, written,
 * reconciled, and managed. It is consumed by:
 *   - `abmind install`  (fresh / already-installed / dry-run)
 *   - `abmind update`   (changed / no-op release activation)
 *   - `abmind service`  (manual subcommands: install, uninstall, start, stop, restart, status)
 *
 * All external side effects go through the `DaemonServiceDeps` injection point
 * so tests use fakes and never touch the real systemd manager.
 */

import { existsSync, readFileSync, mkdirSync, writeFileSync, renameSync, statSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { join } from "node:path";
import { homedir } from "node:os";
import { resolveAbmindHome } from "./paths.js";

// ── Constants ────────────────────────────────────────────────────────────────

export const CANONICAL_SERVICE_NAME = "abmind-daemon";
export const LEGACY_SERVICE_NAME = "abmind";
export const MANAGED_MARKER = "# Managed by abmind (#1453)";
export const UNIT_DIR = join(homedir(), ".config", "systemd", "user");
export const LEGACY_UNIT_PATH = join(UNIT_DIR, `${LEGACY_SERVICE_NAME}.service`);
export const LEGACY_BACKUP_SUFFIX = ".pre-1453";

// ── Types ────────────────────────────────────────────────────────────────────

export interface CommandResult {
  readonly status: number;
  readonly stdout: string;
  readonly stderr: string;
}

export interface DaemonServiceDeps {
  platform: NodeJS.Platform;
  userName: string;
  uid: number;
  nodeExecutable: string;
  abmindHomeOverride: string | undefined;
  publicModuleLink: string;
  fallbackDaemonEntry: string;
  readFile(path: string): string | null;
  writeFileAtomic(path: string, content: string, mode: number): void;
  moveFile(from: string, to: string): void;
  command(name: string, args: readonly string[]): CommandResult;
  canonicalUnitPath: string;
}

export interface EnsureDaemonServiceOptions {
  dryRun: boolean;
  releaseChanged: boolean;
  start: boolean;
}

export type EnsureDaemonServiceResult =
  | { state: "ready"; unitChanged: boolean; action: "started" | "restarted" | "already-running" }
  | { state: "existing-owner"; unitChanged: boolean; waitingServiceStarted: boolean }
  | { state: "unsupported"; reason: string }
  | { state: "needs-linger"; serviceReady: boolean; remediation: string };

// ── Helpers ──────────────────────────────────────────────────────────────────

/** Generate the canonical systemd unit content. */
export function renderUnitContent(deps: { nodeExecutable: string; daemonEntryPath: string; abmindHome: string }): string {
  const escapedNode = quoteSystemdValue(deps.nodeExecutable);
  const escapedEntry = quoteSystemdValue(deps.daemonEntryPath);
  const escapedHome = quoteSystemdValue(deps.abmindHome);
  return `${MANAGED_MARKER}
[Unit]
Description=Abmind memory daemon — owns memory.db, serves local clients
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${escapedNode} ${escapedEntry} --wait-for-owner
WorkingDirectory=${escapedHome}
Environment=ABMIND_HOME=${escapedHome}
UMask=0077
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=default.target
`;
}

/** Resolve the stable daemon entry path. */
export function resolveDaemonEntryPath(publicModuleLink: string, fallbackDaemonEntry: string, pathExists?: (p: string) => boolean): string {
  const moduleEntry = join(publicModuleLink, "dist", "cli", "abmind-daemon.js");
  if ((pathExists ?? existsSync)(moduleEntry)) return moduleEntry;
  return fallbackDaemonEntry;
}

/**
 * Quote a value for embedding in a systemd unit key/value line.
 *
 * systemd values can contain spaces and most special characters if properly
 * quoted. We use double-quoting and escape the few characters that are
 * significant inside double quotes.
 */
export function quoteSystemdValue(value: string): string {
  for (const ch of value) {
    if (ch === "\n" || ch === "\r" || ch === "\0" || ch === "\t") {
      throw new Error(`systemd value contains control character: ${JSON.stringify(value)}`);
    }
  }
  // Double-quote if the value contains spaces or special chars
  if (/[\s"$`\\]/.test(value)) {
    const escaped = value.replace(/["$`\\]/g, "\\$&");
    return `"${escaped}"`;
  }
  return value;
}

/** Determine whether a unit file was generated by abmind. */
export function isManagedUnit(content: string): boolean {
  return content.includes(MANAGED_MARKER);
}

/** Determine whether a unit file matches the known abmind-generated shape (legacy or canonical). */
export function isKnownGeneratedUnit(content: string): boolean {
  const lower = content.toLowerCase();
  return lower.includes("abmind") && (lower.includes("description=abmind memory daemon") || lower.includes("description=abmind memory daemon"));
}

function defaultCanonicalPath(): string {
  return join(UNIT_DIR, `${CANONICAL_SERVICE_NAME}.service`);
}

function defaultDeps(): DaemonServiceDeps {
  const sp = join(resolveAbmindHome(), "packages", "standalone", "current");
  const standaloneLink = join(sp, "node_modules", "abmind");
  const pubLink = join(homedir(), ".local", "lib", "node_modules", "abmind");
  const here = new URL(".", import.meta.url).pathname;
  const fallback = join(here, "..", "cli", "abmind-daemon.js");
  return {
    platform: process.platform,
    userName: process.env["USER"] ?? "unknown",
    uid: typeof process.getuid === "function" ? process.getuid() : 0,
    nodeExecutable: process.execPath,
    abmindHomeOverride: process.env["ABMIND_HOME"],
    publicModuleLink: standaloneLink,
    fallbackDaemonEntry: join(pubLink, "dist", "cli", "abmind-daemon.js"),
    readFile: (p: string) => { try { return readFileSync(p, "utf-8"); } catch { return null; } },
    writeFileAtomic: (p: string, content: string, mode: number) => {
      const dir = p.substring(0, p.lastIndexOf("/"));
      mkdirSync(dir, { recursive: true });
      const tmp = p + ".tmp." + process.pid;
      writeFileSync(tmp, content, { encoding: "utf-8", mode });
      renameSync(tmp, p);
    },
    moveFile: (from: string, to: string) => renameSync(from, to),
    command: (name: string, args: readonly string[]) => {
      const r = spawnSync(name, args, { encoding: "utf-8" });
      return { status: r.status ?? 1, stdout: r.stdout ?? "", stderr: r.stderr ?? "" };
    },
    canonicalUnitPath: defaultCanonicalPath(),
  };
}

// ── Reconciliation ───────────────────────────────────────────────────────────

export type UnitReconciliationAction =
  | { kind: "write-new"; reason: string }
  | { kind: "noop"; reason: string }
  | { kind: "overwrite"; reason: string }
  | { kind: "backup-and-write"; reason: string; backupPath: string }
  | { kind: "migrate-legacy"; reason: string; backupPath: string }
  | { kind: "conflict"; reason: string };

interface ReconciliationPlan {
  action: UnitReconciliationAction;
  canonicalContent: string;
  existCanonical: boolean;
  existLegacy: boolean;
}

export function planUnitReconciliation(
  deps: DaemonServiceDeps,
): ReconciliationPlan {
  const canonicalPath = deps.canonicalUnitPath;
  const entry = resolveDaemonEntryPath(deps.publicModuleLink, deps.fallbackDaemonEntry);
  const canonicalContent = renderUnitContent({
    nodeExecutable: deps.nodeExecutable,
    daemonEntryPath: entry,
    abmindHome: deps.abmindHomeOverride ?? resolveAbmindHome(),
  });

  const existCanonical = deps.readFile(canonicalPath) !== null;
  const existLegacy = deps.readFile(LEGACY_UNIT_PATH) !== null;

  if (!existCanonical && !existLegacy) {
    return {
      action: { kind: "write-new", reason: "no existing unit" },
      canonicalContent,
      existCanonical,
      existLegacy,
    };
  }

  if (existCanonical) {
    const current = deps.readFile(canonicalPath)!;
    if (isManagedUnit(current)) {
      if (current === canonicalContent) {
        return {
          action: { kind: "noop", reason: "managed unit unchanged" },
          canonicalContent,
          existCanonical,
          existLegacy,
        };
      }
      return {
        action: { kind: "overwrite", reason: "managed unit content changed" },
        canonicalContent,
        existCanonical,
        existLegacy,
      };
    }
    // unmanaged canonical unit — back it up first
    const backupPath = backupPathFor(canonicalPath);
    if (existsSync(backupPath)) {
      const backupContent = deps.readFile(backupPath);
      if (backupContent !== current) {
        return {
          action: { kind: "conflict", reason: `unmanaged unit exists at ${canonicalPath} and backup collision at ${backupPath}` },
          canonicalContent,
          existCanonical,
          existLegacy,
        };
      }
    }
    return {
      action: { kind: "backup-and-write", reason: "replacing unmanaged unit", backupPath },
      canonicalContent,
      existCanonical,
      existLegacy,
    };
  }

  // only legacy exists
  const legacyContent = deps.readFile(LEGACY_UNIT_PATH)!;
  if (isKnownGeneratedUnit(legacyContent)) {
    return {
      action: { kind: "migrate-legacy", reason: "replacing known generated legacy unit", backupPath: `${LEGACY_UNIT_PATH}${LEGACY_BACKUP_SUFFIX}` },
      canonicalContent,
      existCanonical,
      existLegacy,
    };
  }
  return {
    action: { kind: "conflict", reason: `unrecognized legacy unit at ${LEGACY_UNIT_PATH} and no canonical unit` },
    canonicalContent,
    existCanonical,
    existLegacy,
  };
}

function backupPathFor(unitPath: string): string {
  const ts = new Date().toISOString().replace(/[:.]/g, "-");
  return `${unitPath}.bak.${ts}`;
}

/** Apply a reconciliation plan. Returns true if the unit file or migration changed. */
export function applyUnitReconciliation(
  plan: ReconciliationPlan,
  deps: DaemonServiceDeps,
  dryRun: boolean,
): boolean {
  const action = plan.action;
  switch (action.kind) {
    case "noop":
      return false;
    case "write-new":
    case "overwrite": {
      if (!dryRun) {
        deps.writeFileAtomic(deps.canonicalUnitPath, plan.canonicalContent, 0o644);
      }
      return true;
    }
    case "backup-and-write": {
      if (!dryRun) {
        const current = deps.readFile(deps.canonicalUnitPath)!;
        deps.writeFileAtomic(action.backupPath, current, 0o644);
        deps.writeFileAtomic(deps.canonicalUnitPath, plan.canonicalContent, 0o644);
      }
      return true;
    }
    case "migrate-legacy": {
      if (!dryRun) {
        // stop + disable legacy before moving it
        deps.command("systemctl", ["--user", "stop", LEGACY_SERVICE_NAME]);
        deps.command("systemctl", ["--user", "disable", LEGACY_SERVICE_NAME]);
        deps.moveFile(LEGACY_UNIT_PATH, action.backupPath);
        deps.writeFileAtomic(deps.canonicalUnitPath, plan.canonicalContent, 0o644);
      }
      return true;
    }
    case "conflict":
      throw new Error(action.reason);
  }
}

// ── systemd state management ────────────────────────────────────────────────

export interface SystemdState {
  /** Whether the systemd user manager is available on this host. */
  available: boolean;
  /** Whether the canonical service is currently active (running). */
  isActive: boolean;
  /** Whether the canonical unit is enabled. */
  isEnabled: boolean;
  /** Whether another daemon process (non-systemd) owns the endpoint.  */
  healthyManualOwner: boolean;
  /** Whether the daemon endpoint is completely unavailable. */
  daemonUnavailable: boolean;
}

/** Probe the systemd user manager and daemon health. */
export function probeSystemdState(deps: DaemonServiceDeps): SystemdState {
  const available = probeSystemdAvailable(deps);
  if (!available) {
    return { available: false, isActive: false, isEnabled: false, healthyManualOwner: false, daemonUnavailable: true };
  }

  const isActive = checkServiceActive(deps, CANONICAL_SERVICE_NAME);
  const isEnabled = checkServiceEnabled(deps, CANONICAL_SERVICE_NAME);

  // Probe daemon via a simple socket check (we don't import the client here to keep deps light)
  const daemonAvailable = probeDaemonEndpoint(deps);
  const healthyManualOwner = !isActive && daemonAvailable;

  return {
    available,
    isActive,
    isEnabled,
    healthyManualOwner,
    daemonUnavailable: !isActive && !daemonAvailable,
  };
}

function probeSystemdAvailable(deps: DaemonServiceDeps): boolean {
  if (deps.platform !== "linux") return false;
  const r = deps.command("systemctl", ["--user", "show-environment"]);
  return r.status === 0;
}

function checkServiceActive(deps: DaemonServiceDeps, name: string): boolean {
  const r = deps.command("systemctl", ["--user", "is-active", name]);
  return r.stdout.trim() === "active";
}

function checkServiceEnabled(deps: DaemonServiceDeps, name: string): boolean {
  const r = deps.command("systemctl", ["--user", "is-enabled", name]);
  return r.stdout.trim() === "enabled";
}

function probeDaemonEndpoint(deps: DaemonServiceDeps): boolean {
  const sockPath = join(resolveAbmindHome(), "run", "abmind.sock");
  if (!existsSync(sockPath)) return false;
  // Socket exists — check if it's recent (< 30s old to avoid stale sockets)
  try {
    const st = statSync(sockPath);
    const age = Date.now() - st.mtimeMs;
    return age < 30_000;
  } catch {
    return false;
  }
}

// ── Linger ───────────────────────────────────────────────────────────────────

export interface LingerState {
  enabled: boolean;
  remediation: string | null;
}

export function checkLinger(deps: DaemonServiceDeps): LingerState {
  try {
    const r = deps.command("loginctl", ["show-user", String(deps.uid), "-p", "Linger", "--value"]);
    if (r.status === 0 && r.stdout.trim() === "yes") {
      return { enabled: true, remediation: null };
    }
    return { enabled: false, remediation: `sudo loginctl enable-linger ${deps.userName}` };
  } catch {
    return { enabled: false, remediation: `sudo loginctl enable-linger ${deps.userName}` };
  }
}

export function enableLinger(deps: DaemonServiceDeps): LingerState {
  try {
    deps.command("loginctl", ["enable-linger", deps.userName]);
    const r = deps.command("loginctl", ["show-user", String(deps.uid), "-p", "Linger", "--value"]);
    if (r.status === 0 && r.stdout.trim() === "yes") {
      return { enabled: true, remediation: null };
    }
  } catch {
    // fall through
  }
  return { enabled: false, remediation: `sudo loginctl enable-linger ${deps.userName}` };
}

// ── Main entry point ─────────────────────────────────────────────────────────

export function ensureDaemonService(
  deps: DaemonServiceDeps,
  opts: EnsureDaemonServiceOptions,
): EnsureDaemonServiceResult {
  if (deps.platform !== "linux") {
    return { state: "unsupported", reason: `platform ${deps.platform} does not use systemd` };
  }

  // 1. Check systemd availability
  if (!probeSystemdAvailable(deps)) {
    return { state: "unsupported", reason: "systemd user manager not available" };
  }

  // 2. Reconcile unit file
  const plan = planUnitReconciliation(deps);
  let unitChanged: boolean;
  try {
    unitChanged = applyUnitReconciliation(plan, deps, opts.dryRun);
  } catch (err) {
    return { state: "unsupported", reason: `unit reconciliation failed: ${err instanceof Error ? err.message : String(err)}` };
  }

  if (opts.dryRun) {
    return { state: "ready", unitChanged, action: "already-running" as const };
  }

  // 3. daemon-reload if unit changed
  if (unitChanged) {
    deps.command("systemctl", ["--user", "daemon-reload"]);
  }

  // 4. Enable the service
  deps.command("systemctl", ["--user", "enable", CANONICAL_SERVICE_NAME]);

  // 5. Determine state and act
  const sysState = probeSystemdState(deps);

  // 5a. Linger
  const linger = enableLinger(deps);
  if (!linger.enabled) {
    return {
      state: "needs-linger",
      serviceReady: true,
      remediation: linger.remediation ?? `sudo loginctl enable-linger ${deps.userName}`,
    };
  }

  if (sysState.isActive) {
    if (opts.releaseChanged) {
      deps.command("systemctl", ["--user", "restart", CANONICAL_SERVICE_NAME]);
      return { state: "ready", unitChanged, action: "restarted" };
    }
    return { state: "ready", unitChanged, action: "already-running" };
  }

  if (sysState.healthyManualOwner) {
    // Start wait-for-owner process alongside the manual owner
    deps.command("systemctl", ["--user", "start", CANONICAL_SERVICE_NAME]);
    return { state: "existing-owner", unitChanged, waitingServiceStarted: true };
  }

  // Unavailable — start fresh
  if (opts.start) {
    deps.command("systemctl", ["--user", "start", CANONICAL_SERVICE_NAME]);
  }
  return { state: "ready", unitChanged, action: "started" };
}

export { defaultDeps };
